version: 1
id: CUTE_2Tops_64SCP
description: 2Tops + 64x64x64 tile
outsideDataWidth: 512
ConvolutionDIM_Max: 65535
Convolution_Input_Height_Weight_Dim_Max: 16383
KernelSizeMax: 15
StrideSizeMax: 3
ApplicationMaxTensorSize: 65535
MMUAddrWidth: 39
LLCSourceMaxNum: 64
Tensor_M: 64
Tensor_N: 64
Tensor_K: 64
Matrix_M: 4
Matrix_N: 4
ReduceWidthByte: 32
ResultWidthByte: 4
ResultFIFODepth: 8
MMUParams:
  vpnBits: 12
  ppnBits: 12
  pgIdxBits: 12
  vaddrBits: 39
  paddrBits: 39
  corePAddrBits: 64
FPEparams:
  MinGroupSize: 16
  MinDataTypeWidth: 4
  ScaleElementWidth: 8

