version: 1
name: cute4tops_scp128_dramsim48
tags: [cute_tensor_v1, shuttle, medium]

chipyard_config: cute4tops_scp128

memory:
  model: dramsim2
  config: dramsim2_ini_48GB_per_s

simulator:
  backend: verilator
  binary: auto
  max_cycles: 800000000
