version: 1
name: cute4tops_shuttle512_d512_v512_m512_sysbus512_membus1_core_dramsim48
tags: [cute_tensor_v1, shuttle, vector]

chipyard_config: cute4tops_shuttle512_d512_v512_m512_sysbus512_membus1_core

memory:
  model: dramsim2
  config: dramsim2_ini_48GB_per_s

simulator:
  backend: verilator
  binary: auto
  max_cycles: 800000000
